//! Opt-in launch audit log (phase 5 of docs/connect-proxy-plan.md).
//!
//! One JSONL record per launch, appended when the child exits; when
//! filtered egress is active the proxy threads append CONNECT verdict
//! records through the same supervisor-side handle. The file lives at
//! `~/.local/share/ai-jail/history.jsonl` -- the sandbox never sees it
//! (it is outside every mount).
//!
//! Logging must never break a launch: write errors warn once and are
//! otherwise ignored. The exception is symlink refusal, which is a
//! security decision and gets `security_warn`.
//!
//! Every record is hash-chained over the raw line bytes as written (no
//! JSON canonicalization): each line carries `seq` (its 0-based line
//! index) and `prev` (sha256 of the previous raw line, null at
//! genesis), so `--audit-verify` re-hashes file bytes directly. Legacy
//! v2.x unchained lines need no migration: the first chained record
//! simply links to the sha256 of the previous raw line, whatever it is.

use std::io::Write;
use std::path::Path;
use std::sync::Mutex;
use std::sync::atomic::{AtomicBool, Ordering};
use std::time::{SystemTime, UNIX_EPOCH};

use crate::output;

/// Audit records generated by ai-jail are small. This generous limit keeps a
/// poisoned JSONL file from making any reader retain unbounded memory.
const MAX_JSONL_RECORD_SIZE: usize = 8 * 1024 * 1024;

pub(crate) struct ShowReport {
    pub total: u64,
    pub invalid: u64,
}

/// Open trusted HOME itself as a pinned directory. HOME and its ancestors may
/// be symlinks; after this starting descriptor is pinned, every component below
/// it is opened without following symlinks. O_NONBLOCK prevents special files
/// such as FIFOs from hanging before O_DIRECTORY rejects them.
fn open_home(home: &Path) -> std::io::Result<std::fs::File> {
    use nix::libc;
    use std::os::fd::FromRawFd;
    use std::os::unix::ffi::OsStrExt;

    if home.as_os_str().is_empty() {
        return Err(std::io::Error::new(
            std::io::ErrorKind::InvalidInput,
            "HOME is empty",
        ));
    }
    let path =
        std::ffi::CString::new(home.as_os_str().as_bytes()).map_err(|_| {
            std::io::Error::new(
                std::io::ErrorKind::InvalidInput,
                "HOME contains a NUL byte",
            )
        })?;
    // SAFETY: path is NUL-terminated and open returns a fresh descriptor.
    let fd = unsafe {
        libc::open(
            path.as_ptr(),
            libc::O_RDONLY
                | libc::O_CLOEXEC
                | libc::O_DIRECTORY
                | libc::O_NONBLOCK,
        )
    };
    if fd < 0 {
        return Err(std::io::Error::last_os_error());
    }
    // SAFETY: open returned a fresh descriptor owned by this function.
    Ok(unsafe { std::fs::File::from_raw_fd(fd) })
}

/// Open one entry relative to a pinned directory, without following symlinks.
fn open_entry(
    parent: &std::fs::File,
    name: &std::ffi::CStr,
    flags: nix::libc::c_int,
) -> std::io::Result<std::fs::File> {
    use nix::libc;
    use std::os::fd::{AsRawFd, FromRawFd};

    // SAFETY: parent is live and name is a NUL-terminated C string. No
    // creation flag is used, so openat does not need a mode argument.
    let fd = unsafe {
        libc::openat(
            parent.as_raw_fd(),
            name.as_ptr(),
            libc::O_RDONLY | libc::O_CLOEXEC | libc::O_NOFOLLOW | flags,
        )
    };
    if fd < 0 {
        return Err(std::io::Error::last_os_error());
    }
    // SAFETY: openat returned a fresh descriptor owned by this function.
    Ok(unsafe { std::fs::File::from_raw_fd(fd) })
}

fn validate_log_file_for_uid(
    file: &std::fs::File,
    effective_uid: u32,
) -> std::io::Result<()> {
    use std::io::{Error, ErrorKind};
    use std::os::unix::fs::MetadataExt;

    let metadata = file.metadata()?;
    if !metadata.is_file() {
        return Err(Error::new(
            ErrorKind::InvalidInput,
            "audit log is not a regular file",
        ));
    }
    if metadata.uid() != effective_uid || metadata.mode() & 0o077 != 0 {
        return Err(Error::new(
            ErrorKind::PermissionDenied,
            "audit log must be owned by this user with no group/other permissions",
        ));
    }
    Ok(())
}

fn validate_log_file(file: &std::fs::File) -> std::io::Result<()> {
    // SAFETY: geteuid has no preconditions.
    validate_log_file_for_uid(file, unsafe { nix::libc::geteuid() })
}

/// Safely open the existing audit log relative to a pinned HOME descriptor.
/// A missing component means no log; all symlink/type/security failures are
/// errors. The returned descriptor is the inode readers must continue using.
pub(crate) fn open_history(
    home: &Path,
) -> std::io::Result<Option<std::fs::File>> {
    use nix::libc;
    use std::io::ErrorKind;

    // HOME itself must exist and be a safe directory. Only a missing child
    // component means that the audit log does not exist.
    let mut parent = open_home(home)?;
    for name in [c".local", c"share", c"ai-jail"] {
        parent = match open_entry(
            &parent,
            name,
            libc::O_DIRECTORY | libc::O_NONBLOCK,
        ) {
            Ok(directory) => directory,
            Err(error) if error.kind() == ErrorKind::NotFound => {
                return Ok(None);
            }
            Err(error) => return Err(error),
        };
    }
    let file = match open_entry(&parent, c"history.jsonl", libc::O_NONBLOCK) {
        Ok(file) => file,
        Err(error) if error.kind() == ErrorKind::NotFound => return Ok(None),
        Err(error) => return Err(error),
    };
    validate_log_file(&file)?;
    Ok(Some(file))
}

struct BoundedRecord {
    bytes: Vec<u8>,
    hash: String,
    oversized: bool,
    terminated: bool,
}

/// Read and drain one complete JSONL record while retaining at most
/// MAX_JSONL_RECORD_SIZE bytes. Hashing is incremental, including bytes that
/// are discarded after the cap, and excludes the trailing newline.
fn read_bounded_record(
    reader: &mut impl std::io::BufRead,
) -> std::io::Result<Option<BoundedRecord>> {
    use sha2::Digest;

    let mut bytes = Vec::new();
    let mut hash = sha2::Sha256::new();
    let mut oversized = false;
    let mut saw_data = false;
    loop {
        let available = reader.fill_buf()?;
        if available.is_empty() {
            if !saw_data {
                return Ok(None);
            }
            return Ok(Some(BoundedRecord {
                bytes,
                hash: format!("{:x}", hash.finalize()),
                oversized,
                terminated: false,
            }));
        }
        let newline = available.iter().position(|byte| *byte == b'\n');
        let take = newline.unwrap_or(available.len());
        let chunk = &available[..take];
        saw_data = true;
        hash.update(chunk);
        let remaining = MAX_JSONL_RECORD_SIZE.saturating_sub(bytes.len());
        bytes.extend_from_slice(&chunk[..chunk.len().min(remaining)]);
        if chunk.len() > remaining {
            oversized = true;
        }
        let consumed = take + usize::from(newline.is_some());
        reader.consume(consumed);
        if newline.is_some() {
            return Ok(Some(BoundedRecord {
                bytes,
                hash: format!("{:x}", hash.finalize()),
                oversized,
                terminated: true,
            }));
        }
    }
}

/// Read existing events only. The writer receives one safe line per record;
/// malformed records are marked and counted, and I/O errors propagate.
pub(crate) fn show(
    home: &Path,
    writer: &mut impl Write,
) -> std::io::Result<Option<ShowReport>> {
    let Some(file) = open_history(home)? else {
        return Ok(None);
    };
    show_file(file, writer).map(Some)
}

fn show_file(
    file: std::fs::File,
    writer: &mut impl Write,
) -> std::io::Result<ShowReport> {
    let mut report = ShowReport {
        total: 0,
        invalid: 0,
    };
    let mut reader = std::io::BufReader::new(file);
    while let Some(record) = read_bounded_record(&mut reader)? {
        report.total += 1;
        let summary = if record.oversized {
            None
        } else {
            // serde_json accepts trailing JSON whitespace, so the historical
            // CRLF behavior remains unchanged even though newline framing is
            // removed by the bounded reader.
            serde_json::from_slice::<serde_json::Value>(&record.bytes)
                .ok()
                .and_then(|record| summarize(&record))
        };
        let summary = summary.unwrap_or_else(|| {
            report.invalid += 1;
            format!("[invalid record at line {}]", report.total)
        });
        let mut safe = String::with_capacity(summary.len());
        for ch in summary.chars() {
            // Also escape Unicode bidi controls and line/paragraph separators.
            if ch.is_control()
                || matches!(
                    ch,
                    '\u{061c}'
                        | '\u{200e}'
                        | '\u{200f}'
                        | '\u{2028}'..='\u{202e}'
                        | '\u{2066}'..='\u{2069}'
                )
            {
                safe.extend(ch.escape_default());
            } else {
                safe.push(ch);
            }
        }
        writeln!(writer, "{safe}")?;
    }
    writer.flush()?;
    Ok(report)
}

fn summarize(record: &serde_json::Value) -> Option<String> {
    let ts = record.get("ts")?.as_str()?;
    let kind = record.get("type")?.as_str()?;
    Some(match kind {
        "launch" => {
            let command = record.get("command")?.as_array()?;
            if !command.iter().all(serde_json::Value::is_string) {
                return None;
            }
            let command = serde_json::to_string(command).ok()?;
            let code = record.get("exit_code")?.as_i64()?;
            let duration = record.get("duration_s")?.as_f64()?;
            format!("{ts}  launch {command}  (exit {code}, {duration:.1}s)")
        }
        "connect" => {
            let host = record.get("host")?.as_str()?;
            let port = u16::try_from(record.get("port")?.as_u64()?).ok()?;
            let verdict = record.get("verdict")?.as_str()?;
            let reason = record.get("reason")?.as_str()?;
            format!("{ts}  connect {host}:{port}  {verdict} ({reason})")
        }
        "secret_inject" => {
            let key = record.get("key")?.as_str()?;
            let host = record.get("host")?.as_str()?;
            let count = record.get("substitutions")?.as_u64()?;
            format!("{ts}  credential {key} -> {host}  ({count} substitutions)")
        }
        _ => format!("{ts}  {kind}  (unrecognized audit record)"),
    })
}

/// Append-only JSONL audit log handle. Cheap to share: the proxy
/// threads hold an `Arc<AuditLog>` clone of the supervisor's handle.
pub(crate) struct AuditLog {
    chain: Mutex<ChainState>,
    warned: AtomicBool,
}

struct ChainState {
    file: std::fs::File,
    /// sha256 of the last line written, as lowercase hex.
    prev: Option<String>,
    seq: u64,
    /// The file on disk did not end with a newline (e.g. truncated
    /// tail): the next append must first terminate that remnant, or the
    /// new record would glue onto it.
    needs_newline: bool,
}

/// What one launch record carries. Kept deliberately small: the same
/// capability summary `ai-jail status` prints, not the whole config.
pub(crate) struct LaunchRecord<'a> {
    pub command: &'a [String],
    pub network_mode: &'static str,
    pub allow_hosts: &'a [String],
    pub lockdown: bool,
    pub agent_state: bool,
    pub gpu: bool,
    pub display: bool,
    pub audio: bool,
    pub kvm: bool,
    pub browser_profile: Option<&'a str>,
    pub project_config: bool,
    pub project_trusted: bool,
    pub global_config: bool,
    pub exit_code: i32,
    pub duration: std::time::Duration,
    /// Resource limits requested for the launch, when any were set.
    pub limits: Option<serde_json::Value>,
    /// What the sandbox cgroup counted (OOM kills, peak memory, ...),
    /// when the launch ran in its own scope.
    pub cgroup: Option<serde_json::Value>,
}

pub(crate) fn sha256_hex(bytes: &[u8]) -> String {
    use sha2::Digest;
    format!("{:x}", sha2::Sha256::digest(bytes))
}

/// Seed the chain from the same inode that will receive appends. Records are
/// bounded in memory and oversized records are still hashed incrementally.
/// Any read failure yields the safe genesis state: logging must never break a
/// launch.
fn seed_chain(file: &std::fs::File) -> (Option<String>, u64, bool) {
    use std::io::{Seek, SeekFrom};

    let Ok(mut file) = file.try_clone() else {
        return (None, 0, false);
    };
    if file.seek(SeekFrom::Start(0)).is_err() {
        return (None, 0, false);
    }
    let mut reader = std::io::BufReader::new(file);
    let mut prev = None;
    let mut seq = 0_u64;
    let mut needs_newline = false;
    loop {
        match read_bounded_record(&mut reader) {
            Ok(Some(record)) => {
                prev = Some(record.hash);
                seq += 1;
                needs_newline = !record.terminated;
            }
            Ok(None) => break,
            Err(_) => return (None, 0, false),
        }
    }
    (prev, seq, needs_newline)
}

fn validate_directory(file: &std::fs::File) -> std::io::Result<()> {
    use nix::libc;
    use std::io::{Error, ErrorKind};
    use std::os::unix::fs::MetadataExt;

    let metadata = file.metadata()?;
    // SAFETY: geteuid has no preconditions.
    if !metadata.is_dir() || metadata.uid() != unsafe { libc::geteuid() } {
        return Err(Error::new(
            ErrorKind::PermissionDenied,
            "audit directory must be a directory owned by this user",
        ));
    }
    Ok(())
}

fn open_or_create_directory(
    parent: &std::fs::File,
    name: &std::ffi::CStr,
) -> std::io::Result<std::fs::File> {
    use nix::libc;
    use std::io::ErrorKind;
    use std::os::fd::AsRawFd;

    let flags = libc::O_DIRECTORY | libc::O_NONBLOCK;
    let directory = match open_entry(parent, name, flags) {
        Ok(directory) => directory,
        Err(error) if error.kind() == ErrorKind::NotFound => {
            // SAFETY: parent and name are valid; mode is used by mkdirat.
            if unsafe {
                libc::mkdirat(parent.as_raw_fd(), name.as_ptr(), 0o700)
            } < 0
            {
                let mkdir_error = std::io::Error::last_os_error();
                if mkdir_error.kind() != ErrorKind::AlreadyExists {
                    return Err(mkdir_error);
                }
            }
            // Re-open after creation (or a racing EEXIST) so no pathname
            // check is trusted and a swapped symlink is rejected.
            open_entry(parent, name, flags)?
        }
        Err(error) => return Err(error),
    };
    validate_directory(&directory)?;
    Ok(directory)
}

fn open_log_for_append(home: &Path) -> std::io::Result<std::fs::File> {
    use nix::libc;
    use std::os::fd::{AsRawFd, FromRawFd};
    use std::os::unix::fs::MetadataExt;

    let mut parent = open_home(home)?;
    validate_directory(&parent)?;
    for name in [c".local", c"share", c"ai-jail"] {
        parent = open_or_create_directory(&parent, name)?;
    }
    // Keep the dedicated audit directory private using its pinned fd.
    // SAFETY: parent is a live descriptor.
    if unsafe { libc::fchmod(parent.as_raw_fd(), 0o700) } < 0 {
        return Err(std::io::Error::last_os_error());
    }

    // SAFETY: parent and name are valid. O_CREAT supplies mode 0600 and the
    // returned descriptor is fresh and owned by this function.
    let fd = unsafe {
        libc::openat(
            parent.as_raw_fd(),
            c"history.jsonl".as_ptr(),
            libc::O_RDWR
                | libc::O_APPEND
                | libc::O_CREAT
                | libc::O_CLOEXEC
                | libc::O_NOFOLLOW
                | libc::O_NONBLOCK,
            0o600,
        )
    };
    if fd < 0 {
        return Err(std::io::Error::last_os_error());
    }
    // SAFETY: openat returned a fresh descriptor.
    let file = unsafe { std::fs::File::from_raw_fd(fd) };
    let metadata = file.metadata()?;
    // SAFETY: geteuid and fchmod have no additional preconditions here.
    if !metadata.is_file() || metadata.uid() != unsafe { libc::geteuid() } {
        return Err(std::io::Error::new(
            std::io::ErrorKind::PermissionDenied,
            "audit log must be a regular file owned by this user",
        ));
    }
    if unsafe { libc::fchmod(file.as_raw_fd(), 0o600) } < 0 {
        return Err(std::io::Error::last_os_error());
    }
    validate_log_file(&file)?;
    Ok(file)
}

fn is_security_open_error(error: &std::io::Error) -> bool {
    use nix::libc;

    matches!(
        error.raw_os_error(),
        Some(
            libc::ELOOP
                | libc::ENOTDIR
                | libc::EISDIR
                | libc::EACCES
                | libc::EPERM
        )
    ) || matches!(
        error.kind(),
        std::io::ErrorKind::InvalidInput | std::io::ErrorKind::PermissionDenied
    )
}

impl AuditLog {
    /// Open the log under trusted `home`, creating descriptor-relative
    /// directories and the file without following symlinks below HOME.
    /// Security failures disable logging with a security warning; ordinary I/O
    /// failures remain best-effort.
    pub(crate) fn open(home: &Path) -> Option<std::sync::Arc<AuditLog>> {
        let path = home.join(".local/share/ai-jail/history.jsonl");
        let file = match open_log_for_append(home) {
            Ok(file) => file,
            Err(error) => {
                let message = format!(
                    "audit log disabled: cannot open {}: {error}",
                    path.display()
                );
                if is_security_open_error(&error) {
                    output::security_warn(&message);
                } else {
                    output::warn(&message);
                }
                return None;
            }
        };
        let (prev, seq, needs_newline) = seed_chain(&file);
        Some(std::sync::Arc::new(AuditLog {
            chain: Mutex::new(ChainState {
                file,
                prev,
                seq,
                needs_newline,
            }),
            warned: AtomicBool::new(false),
        }))
    }

    /// Append one JSON record. Write errors warn once and are dropped:
    /// logging must not break sandboxes.
    ///
    /// The `seq`/`prev` chain fields are inserted here, not in the
    /// record builders, so every record type participates unchanged.
    pub(crate) fn record(&self, entry: serde_json::Value) {
        let mut entry = entry;
        let mut state = self.chain.lock().unwrap();
        if let Some(obj) = entry.as_object_mut() {
            obj.insert("seq".to_string(), state.seq.into());
            obj.insert(
                "prev".to_string(),
                state
                    .prev
                    .as_deref()
                    .map_or(serde_json::Value::Null, |p| p.into()),
            );
        }
        // The chain hashes the raw line bytes as written, without the
        // trailing newline.
        let mut line = entry.to_string();
        let hash = sha256_hex(line.as_bytes());
        line.push('\n');
        if state.needs_newline {
            line.insert(0, '\n');
            state.needs_newline = false;
        }
        let result = state.file.write_all(line.as_bytes());
        if result.is_err() && !self.warned.swap(true, Ordering::SeqCst) {
            output::warn("audit log write failed; further errors suppressed");
        }
        if result.is_ok() {
            state.prev = Some(hash);
            state.seq += 1;
        }
    }
}

/// RFC3339 (UTC, second precision) from std alone -- no chrono. The
/// civil-date conversion is Howard Hinnant's days-from-civil algorithm.
fn rfc3339(now: SystemTime) -> String {
    let secs = now.duration_since(UNIX_EPOCH).unwrap_or_default().as_secs();
    let days = (secs / 86400) as i64;
    let rem = secs % 86400;
    let (hour, min, sec) = (rem / 3600, (rem % 3600) / 60, rem % 60);
    let z = days + 719_468;
    let era = z.div_euclid(146_097);
    let doe = z.rem_euclid(146_097);
    let yoe = (doe - doe / 1460 + doe / 36_524 - doe / 146_096) / 365;
    let year = yoe + era * 400;
    let doy = doe - (365 * yoe + yoe / 4 - yoe / 100);
    let mp = (5 * doy + 2) / 153;
    let day = doy - (153 * mp + 2) / 5 + 1;
    let month = if mp < 10 { mp + 3 } else { mp - 9 };
    let year = if month <= 2 { year + 1 } else { year };
    format!("{year:04}-{month:02}-{day:02}T{hour:02}:{min:02}:{sec:02}Z")
}

/// One launch record: who ran, with which effective capabilities, from
/// which config sources, and how it ended.
pub(crate) fn launch_record(record: &LaunchRecord<'_>) -> serde_json::Value {
    serde_json::json!({
        "ts": rfc3339(SystemTime::now()),
        "type": "launch",
        "command": record.command,
        "network": record.network_mode,
        "allow_hosts": record.allow_hosts,
        "lockdown": record.lockdown,
        "agent_state": record.agent_state,
        "gpu": record.gpu,
        "display": record.display,
        "audio": record.audio,
        "kvm": record.kvm,
        "browser_profile": record.browser_profile,
        "config": {
            "project": record.project_config,
            "project_trusted": record.project_trusted,
            "global": record.global_config,
        },
        "exit_code": record.exit_code,
        "duration_s": record.duration.as_millis() as f64 / 1000.0,
        "limits": record.limits,
        "cgroup": record.cgroup,
    })
}

/// One proxy CONNECT verdict record (filtered egress only).
pub(crate) fn connect_record(
    host: &str,
    port: u16,
    verdict: &str,
    reason: &str,
) -> serde_json::Value {
    serde_json::json!({
        "ts": rfc3339(SystemTime::now()),
        "type": "connect",
        "host": host,
        "port": port,
        "verdict": verdict,
        "reason": reason,
    })
}

/// One phantom-credential substitution record (filtered egress +
/// `--secret`). Names the host, the env var, and the substitution
/// count -- never a value, real or placeholder.
pub(crate) fn secret_inject_record(
    host: &str,
    key: &str,
    substitutions: usize,
) -> serde_json::Value {
    serde_json::json!({
        "ts": rfc3339(SystemTime::now()),
        "type": "secret_inject",
        "host": host,
        "key": key,
        "substitutions": substitutions,
    })
}

/// Outcome of [`verify`]: line counts and the first chain break.
pub(crate) struct VerifyReport {
    /// Lines in the file.
    pub total: u64,
    /// Lines carrying `seq`/`prev` chain fields.
    pub chained: u64,
    /// Valid JSON lines without chain fields (pre-chain records).
    pub legacy: u64,
    /// 1-based number of the first offending line, if any.
    pub first_break: Option<u64>,
}

/// Verify the hash chain of an audit log, line by line (1-based):
///
/// - a line that is not valid JSON is a break (a corrupt record --
///   e.g. a truncated tail) and counts as neither chained nor legacy;
/// - a valid JSON line without both `seq` and `prev` fields is a
///   legacy (pre-chain) record and re-seeds the chain expectation from
///   its own raw bytes;
/// - a chained line breaks when its `prev` is not the sha256 of the
///   previous raw line (genesis, line 1, expects null) or its `seq` is
///   not the line's 0-based index.
///
/// Every expectation is computed from the actual bytes on disk, so a
/// break does not cascade: `first_break` is the first offending line.
pub(crate) fn verify(file: std::fs::File) -> std::io::Result<VerifyReport> {
    let mut reader = std::io::BufReader::new(file);
    let mut report = VerifyReport {
        total: 0,
        chained: 0,
        legacy: 0,
        first_break: None,
    };
    let mut prev_hash: Option<String> = None;
    while let Some(record) = read_bounded_record(&mut reader)? {
        report.total += 1;
        let parsed: Option<serde_json::Value> = if record.oversized {
            None
        } else {
            serde_json::from_slice(&record.bytes).ok()
        };
        let chain_fields =
            parsed.as_ref().and_then(|v| v.as_object()).and_then(|obj| {
                let seq = obj.get("seq")?.as_u64()?;
                let prev = obj.get("prev")?;
                Some((seq, prev))
            });
        match chain_fields {
            None if parsed.is_none() => {
                // Corrupt or oversized record: not verifiable as anything.
                if report.first_break.is_none() {
                    report.first_break = Some(report.total);
                }
            }
            None => {
                report.legacy += 1;
            }
            Some((seq, prev)) => {
                report.chained += 1;
                let prev_matches = match (&prev_hash, prev) {
                    (None, serde_json::Value::Null) => true,
                    (Some(expected), serde_json::Value::String(actual)) => {
                        expected == actual
                    }
                    _ => false,
                };
                let seq_matches = seq == report.total - 1;
                if !(prev_matches && seq_matches)
                    && report.first_break.is_none()
                {
                    report.first_break = Some(report.total);
                }
            }
        }
        prev_hash = Some(record.hash);
    }
    Ok(report)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::os::unix::fs::PermissionsExt;
    use std::path::PathBuf;

    fn test_home(name: &str) -> PathBuf {
        let home = std::env::temp_dir()
            .join(format!("ai-jail-audit-{name}-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&home);
        std::fs::create_dir_all(&home).unwrap();
        home
    }

    fn log_path(home: &Path) -> PathBuf {
        home.join(".local/share/ai-jail/history.jsonl")
    }

    #[test]
    fn rfc3339_shape_and_known_epoch() {
        // 1970-01-01T00:00:00Z
        assert_eq!(rfc3339(UNIX_EPOCH), "1970-01-01T00:00:00Z");
        // 1_789_094_096 s past the epoch is 2026-09-11T02:34:56Z.
        let ts =
            rfc3339(UNIX_EPOCH + std::time::Duration::from_secs(1_789_094_096));
        assert_eq!(ts, "2026-09-11T02:34:56Z");
        assert_eq!(rfc3339(SystemTime::now()).len(), 20);
    }

    #[test]
    fn open_creates_dir_and_file_with_private_modes() {
        let home = test_home("create");
        let log = AuditLog::open(&home).expect("open should succeed");
        let dir_mode = std::fs::metadata(log_path(&home).parent().unwrap())
            .unwrap()
            .permissions()
            .mode()
            & 0o777;
        assert_eq!(dir_mode, 0o700);
        log.record(serde_json::json!({"probe": true}));
        drop(log);
        let file_mode = std::fs::metadata(log_path(&home))
            .unwrap()
            .permissions()
            .mode()
            & 0o777;
        assert_eq!(file_mode, 0o600);
        let content = std::fs::read_to_string(log_path(&home)).unwrap();
        let line: serde_json::Value =
            serde_json::from_str(content.trim()).unwrap();
        assert_eq!(line["probe"], true);
        let _ = std::fs::remove_dir_all(&home);
    }

    #[test]
    fn open_refuses_symlinked_directory() {
        let home = test_home("dir-symlink");
        let target = test_home("dir-symlink-target");
        std::fs::create_dir_all(home.join(".local/share")).unwrap();
        std::os::unix::fs::symlink(&target, home.join(".local/share/ai-jail"))
            .unwrap();
        assert!(AuditLog::open(&home).is_none());
        // Nothing was written through the link.
        assert!(!log_path(&target).exists());
        let _ = std::fs::remove_dir_all(&home);
        let _ = std::fs::remove_dir_all(&target);
    }

    #[test]
    fn open_refuses_symlinked_file() {
        let home = test_home("file-symlink");
        let outside = test_home("file-symlink-outside").join("victim");
        std::fs::write(&outside, b"").unwrap();
        let dir = home.join(".local/share/ai-jail");
        std::fs::create_dir_all(&dir).unwrap();
        std::os::unix::fs::symlink(&outside, dir.join("history.jsonl"))
            .unwrap();
        assert!(AuditLog::open(&home).is_none());
        assert!(std::fs::read_to_string(&outside).unwrap().is_empty());
        let _ = std::fs::remove_dir_all(&home);
        let _ = std::fs::remove_dir_all(outside.parent().unwrap());
    }

    #[test]
    fn launch_and_connect_records_are_json_lines() {
        let home = test_home("records");
        let log = AuditLog::open(&home).unwrap();
        let launch = LaunchRecord {
            command: &["claude".to_string(), "--continue".to_string()],
            network_mode: "filtered",
            allow_hosts: &["api.anthropic.com".to_string()],
            lockdown: false,
            agent_state: true,
            gpu: false,
            display: false,
            audio: false,
            kvm: false,
            browser_profile: None,
            project_config: true,
            project_trusted: false,
            global_config: true,
            exit_code: 0,
            duration: std::time::Duration::from_millis(1500),
            limits: Some(serde_json::json!({"memory": 1024})),
            cgroup: Some(serde_json::json!({"oom_kills": 1})),
        };
        log.record(launch_record(&launch));
        log.record(connect_record(
            "api.anthropic.com",
            443,
            "allow",
            "in-allowlist",
        ));
        drop(log);
        let content = std::fs::read_to_string(log_path(&home)).unwrap();
        let lines: Vec<serde_json::Value> = content
            .lines()
            .map(|line| serde_json::from_str(line).unwrap())
            .collect();
        assert_eq!(lines.len(), 2);
        assert_eq!(lines[0]["type"], "launch");
        assert_eq!(lines[0]["command"][0], "claude");
        assert_eq!(lines[0]["network"], "filtered");
        assert_eq!(lines[0]["exit_code"], 0);
        assert_eq!(lines[0]["duration_s"], 1.5);
        assert_eq!(lines[0]["limits"]["memory"], 1024);
        assert_eq!(lines[0]["cgroup"]["oom_kills"], 1);
        assert_eq!(lines[1]["type"], "connect");
        assert_eq!(lines[1]["host"], "api.anthropic.com");
        assert_eq!(lines[1]["verdict"], "allow");
        let _ = std::fs::remove_dir_all(&home);
    }

    fn probe(log: &AuditLog, n: u64) {
        log.record(serde_json::json!({"probe": n}));
    }

    #[test]
    fn genesis_record_has_null_prev_and_seq_zero() {
        let home = test_home("genesis");
        let log = AuditLog::open(&home).unwrap();
        probe(&log, 1);
        drop(log);
        let content = std::fs::read_to_string(log_path(&home)).unwrap();
        let line: serde_json::Value =
            serde_json::from_str(content.trim()).unwrap();
        assert_eq!(line["seq"], 0);
        assert_eq!(line["prev"], serde_json::Value::Null);
        let report =
            verify(std::fs::File::open(log_path(&home)).unwrap()).unwrap();
        assert_eq!(report.total, 1);
        assert_eq!(report.chained, 1);
        assert_eq!(report.legacy, 0);
        assert_eq!(report.first_break, None);
        let _ = std::fs::remove_dir_all(&home);
    }

    #[test]
    fn chain_survives_drop_and_reopen() {
        let home = test_home("reopen");
        let log = AuditLog::open(&home).unwrap();
        probe(&log, 1);
        probe(&log, 2);
        drop(log);

        // Re-open: the chain seeds from the last line on disk.
        let log = AuditLog::open(&home).unwrap();
        probe(&log, 3);
        drop(log);

        let content = std::fs::read_to_string(log_path(&home)).unwrap();
        let lines: Vec<serde_json::Value> = content
            .lines()
            .map(|line| serde_json::from_str(line).unwrap())
            .collect();
        assert_eq!(lines.len(), 3);
        let seqs: Vec<u64> =
            lines.iter().map(|l| l["seq"].as_u64().unwrap()).collect();
        assert_eq!(seqs, vec![0, 1, 2]);
        let raw: Vec<&str> = content.lines().collect();
        assert_eq!(
            lines[1]["prev"].as_str().unwrap(),
            sha256_hex(raw[0].as_bytes())
        );
        assert_eq!(
            lines[2]["prev"].as_str().unwrap(),
            sha256_hex(raw[1].as_bytes())
        );
        let report =
            verify(std::fs::File::open(log_path(&home)).unwrap()).unwrap();
        assert_eq!(report.first_break, None);
        assert_eq!(report.chained, 3);
        let _ = std::fs::remove_dir_all(&home);
    }

    #[test]
    fn verify_detects_tampered_middle_line() {
        let home = test_home("tamper");
        let log = AuditLog::open(&home).unwrap();
        for n in 1..=3 {
            probe(&log, n);
        }
        drop(log);

        // Rewrite line 2's payload, keeping it valid JSON. Its own
        // seq/prev still check out; the break surfaces at line 3, whose
        // prev no longer matches the bytes now on disk.
        let path = log_path(&home);
        let content = std::fs::read_to_string(&path).unwrap();
        let tampered = content.replacen("\"probe\":2", "\"probe\":99", 1);
        std::fs::write(&path, tampered).unwrap();

        let report = verify(std::fs::File::open(&path).unwrap()).unwrap();
        assert_eq!(report.first_break, Some(3));
        assert_eq!(report.total, 3);
        let _ = std::fs::remove_dir_all(&home);
    }

    #[test]
    fn verify_legacy_only_file_is_intact() {
        let home = test_home("legacy");
        let path = log_path(&home);
        std::fs::create_dir_all(path.parent().unwrap()).unwrap();
        std::fs::write(
            &path,
            "{\"ts\":\"2026-01-01T00:00:00Z\",\"type\":\"launch\"}\n\
             {\"ts\":\"2026-01-01T00:01:00Z\",\"type\":\"launch\"}\n",
        )
        .unwrap();
        let report = verify(std::fs::File::open(&path).unwrap()).unwrap();
        assert_eq!(report.total, 2);
        assert_eq!(report.legacy, 2);
        assert_eq!(report.chained, 0);
        assert_eq!(report.first_break, None);
        let _ = std::fs::remove_dir_all(&home);
    }

    #[test]
    fn append_after_legacy_line_chains_from_its_bytes() {
        let home = test_home("legacy-append");
        let path = log_path(&home);
        std::fs::create_dir_all(path.parent().unwrap()).unwrap();
        let legacy = "{\"ts\":\"2026-01-01T00:00:00Z\",\"type\":\"launch\"}";
        std::fs::write(&path, format!("{legacy}\n")).unwrap();

        let log = AuditLog::open(&home).unwrap();
        probe(&log, 1);
        drop(log);

        let content = std::fs::read_to_string(&path).unwrap();
        let lines: Vec<serde_json::Value> = content
            .lines()
            .map(|line| serde_json::from_str(line).unwrap())
            .collect();
        assert_eq!(lines.len(), 2);
        // The first chained record links to the legacy line's bytes.
        assert_eq!(lines[1]["seq"], 1);
        assert_eq!(
            lines[1]["prev"].as_str().unwrap(),
            sha256_hex(legacy.as_bytes())
        );
        let report = verify(std::fs::File::open(&path).unwrap()).unwrap();
        assert_eq!(report.first_break, None);
        assert_eq!(report.legacy, 1);
        assert_eq!(report.chained, 1);
        let _ = std::fs::remove_dir_all(&home);
    }

    #[test]
    fn verify_counts_valid_record_after_oversized_break() {
        let home = test_home("oversized-verify");
        let path = log_path(&home);
        std::fs::create_dir_all(path.parent().unwrap()).unwrap();
        let mut content = vec![b'x'; MAX_JSONL_RECORD_SIZE + 1];
        content.extend_from_slice(b"\n{\"ts\":\"now\",\"type\":\"legacy\"}\n");
        std::fs::write(&path, content).unwrap();
        let report = verify(std::fs::File::open(&path).unwrap()).unwrap();
        assert_eq!(report.total, 2);
        assert_eq!(report.legacy, 1);
        assert_eq!(report.chained, 0);
        assert_eq!(report.first_break, Some(1));
        let _ = std::fs::remove_dir_all(&home);
    }

    #[test]
    fn verify_detects_truncated_tail_after_append() {
        let home = test_home("truncate");
        let log = AuditLog::open(&home).unwrap();
        probe(&log, 1);
        probe(&log, 2);
        drop(log);

        // Cut the tail of the last line: no longer valid JSON.
        let path = log_path(&home);
        let content = std::fs::read_to_string(&path).unwrap();
        std::fs::write(&path, &content[..content.len() - 20]).unwrap();

        // A later append chains from the truncated bytes, but verify
        // flags the corrupt line itself.
        let log = AuditLog::open(&home).unwrap();
        probe(&log, 3);
        drop(log);

        let report = verify(std::fs::File::open(&path).unwrap()).unwrap();
        assert_eq!(report.first_break, Some(2));
        assert_eq!(report.total, 3);
        assert_eq!(report.chained, 2);
        let _ = std::fs::remove_dir_all(&home);
    }

    #[test]
    fn bounded_reader_drains_oversized_records_and_continues() {
        use std::io::{BufReader, Cursor};

        let mut input = vec![b'x'; MAX_JSONL_RECORD_SIZE + 17];
        input.extend_from_slice(b"\n{\"ok\":true}\n");
        // A deliberately awkward capacity exercises records and delimiters
        // crossing fill_buf boundaries.
        let mut reader = BufReader::with_capacity(31, Cursor::new(input));
        let first = read_bounded_record(&mut reader).unwrap().unwrap();
        assert!(first.oversized);
        assert_eq!(first.bytes.len(), MAX_JSONL_RECORD_SIZE);
        assert!(first.terminated);
        let second = read_bounded_record(&mut reader).unwrap().unwrap();
        assert!(!second.oversized);
        assert_eq!(second.bytes, br#"{"ok":true}"#);
        assert!(read_bounded_record(&mut reader).unwrap().is_none());
    }

    #[test]
    fn bounded_reader_accepts_exact_cap_across_fill_boundaries() {
        use std::io::{BufReader, Cursor};

        let mut input = vec![b'x'; MAX_JSONL_RECORD_SIZE];
        input.push(b'\n');
        let mut reader = BufReader::with_capacity(4093, Cursor::new(input));
        let record = read_bounded_record(&mut reader).unwrap().unwrap();
        assert!(!record.oversized);
        assert!(record.terminated);
        assert_eq!(record.bytes.len(), MAX_JSONL_RECORD_SIZE);
        assert!(read_bounded_record(&mut reader).unwrap().is_none());
    }

    #[test]
    fn bounded_reader_accepts_final_record_and_bounds_oversized_tail() {
        use std::io::Cursor;

        let mut reader = Cursor::new(vec![b'x'; MAX_JSONL_RECORD_SIZE + 1]);
        let record = read_bounded_record(&mut reader).unwrap().unwrap();
        assert!(record.oversized);
        assert!(!record.terminated);
        assert_eq!(record.bytes.len(), MAX_JSONL_RECORD_SIZE);
    }

    #[test]
    fn bounded_reader_caps_each_record_not_the_whole_log() {
        use std::io::Cursor;

        let line = vec![b'x'; 1024 * 1024];
        let mut input = Vec::new();
        for _ in 0..9 {
            input.extend_from_slice(&line);
            input.push(b'\n');
        }
        let mut reader = Cursor::new(input);
        for _ in 0..9 {
            let record = read_bounded_record(&mut reader).unwrap().unwrap();
            assert!(!record.oversized);
            assert_eq!(record.bytes.len(), line.len());
        }
        assert!(read_bounded_record(&mut reader).unwrap().is_none());
    }

    #[test]
    fn append_after_oversized_tail_uses_full_hash_and_newline_framing() {
        let home = test_home("oversized-seed");
        let path = log_path(&home);
        std::fs::create_dir_all(path.parent().unwrap()).unwrap();
        let oversized = vec![b'x'; MAX_JSONL_RECORD_SIZE + 1];
        std::fs::write(&path, &oversized).unwrap();

        let log = AuditLog::open(&home).unwrap();
        probe(&log, 7);
        drop(log);

        let content = std::fs::read(&path).unwrap();
        assert_eq!(&content[..oversized.len()], oversized.as_slice());
        assert_eq!(content[oversized.len()], b'\n');
        let appended: serde_json::Value =
            serde_json::from_slice(&content[oversized.len() + 1..]).unwrap();
        assert_eq!(appended["seq"], 1);
        assert_eq!(
            appended["prev"].as_str(),
            Some(sha256_hex(&oversized).as_str())
        );
        let _ = std::fs::remove_dir_all(&home);
    }

    #[test]
    fn opened_descriptors_and_writer_survive_path_replacement() {
        let home = test_home("descriptor-stability");
        let path = log_path(&home);
        std::fs::create_dir_all(path.parent().unwrap()).unwrap();
        let original = b"{\"ts\":\"ORIGINAL\",\"type\":\"future\"}\n";
        std::fs::write(&path, original).unwrap();
        std::fs::set_permissions(
            &path,
            std::os::unix::fs::PermissionsExt::from_mode(0o600),
        )
        .unwrap();
        let log = AuditLog::open(&home).unwrap();
        let verify_fd = open_history(&home).unwrap().unwrap();
        let show_fd = open_history(&home).unwrap().unwrap();

        let moved = path.with_extension("original");
        std::fs::rename(&path, &moved).unwrap();
        let replacement = b"{\"ts\":\"REPLACEMENT\",\"type\":\"future\"}\n";
        std::fs::write(&path, replacement).unwrap();
        std::fs::set_permissions(
            &path,
            std::os::unix::fs::PermissionsExt::from_mode(0o600),
        )
        .unwrap();

        // The writer was opened before the rename and must append to that
        // inode, not reopen the replacement pathname.
        probe(&log, 9);
        drop(log);
        assert_eq!(std::fs::read(&path).unwrap(), replacement);
        let moved_content = std::fs::read(&moved).unwrap();
        assert!(moved_content.starts_with(original));
        let appended: serde_json::Value =
            serde_json::from_slice(&moved_content[original.len()..]).unwrap();
        assert_eq!(appended["probe"], 9);
        assert_eq!(appended["seq"], 1);
        assert_eq!(
            appended["prev"].as_str(),
            Some(sha256_hex(original.strip_suffix(b"\n").unwrap()).as_str())
        );

        // Both reader descriptors likewise remain pinned to ORIGINAL and see
        // its later append. The replacement would have only one legacy line.
        let report = verify(verify_fd).unwrap();
        assert_eq!(report.total, 2);
        assert_eq!(report.legacy, 1);
        assert_eq!(report.chained, 1);
        assert_eq!(report.first_break, None);
        let mut output = Vec::new();
        let report = show_file(show_fd, &mut output).unwrap();
        assert_eq!(report.total, 2);
        assert_eq!(report.invalid, 1);
        assert_eq!(
            String::from_utf8(output).unwrap(),
            "ORIGINAL  future  (unrecognized audit record)\n\
             [invalid record at line 2]\n"
        );
        let _ = std::fs::remove_dir_all(&home);
    }

    #[test]
    fn owner_validation_refuses_mismatched_effective_uid() {
        use std::io::ErrorKind;
        use std::os::unix::fs::{MetadataExt, PermissionsExt};

        let home = test_home("owner-mismatch");
        let path = home.join("log");
        std::fs::write(&path, b"").unwrap();
        std::fs::set_permissions(&path, std::fs::Permissions::from_mode(0o600))
            .unwrap();
        let file = std::fs::File::open(&path).unwrap();
        let owner = file.metadata().unwrap().uid();
        assert!(validate_log_file_for_uid(&file, owner).is_ok());
        let error = validate_log_file_for_uid(&file, owner.wrapping_add(1))
            .unwrap_err();
        assert_eq!(error.kind(), ErrorKind::PermissionDenied);
        let _ = std::fs::remove_dir_all(&home);
    }

    #[test]
    fn writer_supports_trusted_symlinked_home_spellings() {
        let root = test_home("writer-symlink-home");
        let real_home = root.join("real-home");
        std::fs::create_dir(&real_home).unwrap();
        let home = root.join("home");
        std::os::unix::fs::symlink(&real_home, &home).unwrap();
        let ancestor = root.join("ancestor-link");
        std::os::unix::fs::symlink(&root, &ancestor).unwrap();

        for (index, spelling) in [
            home.clone(),
            PathBuf::from(format!("{}/", home.display())),
            home.join("."),
            ancestor.join("home"),
        ]
        .into_iter()
        .enumerate()
        {
            let log = AuditLog::open(&spelling).unwrap();
            probe(&log, index as u64);
        }
        assert_eq!(
            std::fs::read_to_string(log_path(&real_home))
                .unwrap()
                .lines()
                .count(),
            4
        );
        let _ = std::fs::remove_dir_all(&root);
    }

    #[test]
    fn open_refuses_non_directory_component_and_fifo_log() {
        use std::os::unix::ffi::OsStrExt;

        let home = test_home("component-file");
        std::fs::write(home.join(".local"), b"not a directory").unwrap();
        assert!(AuditLog::open(&home).is_none());
        let _ = std::fs::remove_dir_all(&home);

        let home = test_home("fifo-log");
        let path = log_path(&home);
        std::fs::create_dir_all(path.parent().unwrap()).unwrap();
        let c_path =
            std::ffi::CString::new(path.as_os_str().as_bytes()).unwrap();
        // SAFETY: c_path is a valid NUL-terminated string.
        assert_eq!(unsafe { nix::libc::mkfifo(c_path.as_ptr(), 0o600) }, 0);
        assert!(AuditLog::open(&home).is_none());
        let _ = std::fs::remove_dir_all(&home);
    }
}
